/* eslint-disable @typescript-eslint/no-unused-vars */
import React, { useState } from 'react';
import { IconButton, Tooltip } from '@mui/material';
import { TextProps, TextPropsSchema } from '@digitalc/block-text';
import MarkdownEditor from '@uiw/react-markdown-editor';
import request from '../../../../utils/commonRequest';

import BaseSidebarPanel from './helpers/BaseSidebarPanel';
import BooleanInput from './helpers/inputs/BooleanInput';
import TextInput from './helpers/inputs/TextInput';
import MultiStylePropertyPanel from './helpers/style-inputs/MultiStylePropertyPanel';
import CascadingMenu from './CascadingMenu/CascadingMenu';

type TextSidebarPanelProps = {
  data: TextProps;
  setData: (v: TextProps) => void;
};

let macroItem = [
  {
    macroId: 1,
    macroScriptId: 1,
    macroCode: 'CAMPAIGN_NAME',
    macroName: 'CAMPAIGN_NAME',
    macroKey: 'CAMPAIGN_NAME',
    spId: 0,
    comments: 'CAMPAIGN_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CAMPAIGN_NAME',
    valueScript: 'No need CAMPAIGN_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2,
    macroScriptId: 2,
    macroCode: 'START_DATE',
    macroName: 'START_DATE',
    macroKey: 'START_DATE',
    spId: 0,
    comments: 'START_DATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'START_DATE',
    valueScript: 'No need START_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 3,
    macroScriptId: 3,
    macroCode: 'END_DATE',
    macroName: 'END_DATE',
    macroKey: 'END_DATE',
    spId: 0,
    comments: 'END_DATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'END_DATE',
    valueScript: 'No need END_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 4,
    macroScriptId: 4,
    macroCode: 'OFFER_NAME',
    macroName: 'OFFER_NAME',
    macroKey: 'OFFER_NAME',
    spId: 0,
    comments: 'OFFER_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'OFFER_NAME',
    valueScript: 'No need OFFER_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 5,
    macroScriptId: 5,
    macroCode: 'RESPONSE_CODE',
    macroName: 'RESPONSE_CODE',
    macroKey: 'RESPONSE_CODE',
    spId: 0,
    comments: 'RESPONSE_CODE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'RESPONSE_CODE',
    valueScript: 'No need RESPONSE_CODE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 6,
    macroScriptId: 6,
    macroCode: 'SUBS_ID',
    macroName: 'SUBS_ID',
    macroKey: 'SUBS_ID',
    spId: 0,
    comments: 'SUBS_ID',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'SUBS_ID',
    valueScript: 'No need SUBS_ID script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 7,
    macroScriptId: 7,
    macroCode: 'ACC_NBR',
    macroName: 'ACC_NBR',
    macroKey: 'ACC_NBR',
    spId: 0,
    comments: 'ACC_NBR',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'ACC_NBR',
    valueScript: 'No need ACC_NBR script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 8,
    macroScriptId: 8,
    macroCode: 'CUST_NAME',
    macroName: 'CUST_NAME',
    macroKey: 'CUST_NAME',
    spId: 0,
    comments: 'CUST_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CUST_NAME',
    valueScript: 'No need CUST_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 13,
    macroScriptId: 13,
    macroCode: 'QST_NAIRE_URL',
    macroName: 'QST_NAIRE_URL',
    macroKey: 'QST_NAIRE_URL',
    spId: 0,
    comments: 'QST_NAIRE_URL',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'QST_NAIRE_URL',
    valueScript: 'No need QST_NAIRE_URL script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 16,
    macroScriptId: 16,
    macroCode: 'CONFIGED_END_DATE',
    macroName: 'CONFIGED_END_DATE',
    macroKey: 'CONFIGED_END_DATE',
    spId: 0,
    comments: 'CONFIGED_END_DATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CONFIGED_END_DATE',
    valueScript: 'configedEndDateParamServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: 'Y',
    adviceMacroScript: null,
  },
  {
    macroId: 17,
    macroScriptId: 17,
    macroCode: 'CONTACT_ID',
    macroName: 'CONTACT_ID',
    macroKey: 'CONTACT_ID',
    spId: 0,
    comments: 'CONTACT_ID',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CONTACT_ID',
    valueScript: 'No need CONTACT_ID script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 18,
    macroScriptId: 18,
    macroCode: 'APP_DEEP_LINK',
    macroName: 'APP_DEEP_LINK',
    macroKey: 'APP_DEEP_LINK',
    spId: 0,
    comments: 'APP_DEEP_LINK',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'APP_DEEP_LINK',
    valueScript: 'appDeepLinkServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 19,
    macroScriptId: 19,
    macroCode: 'VOUCHER_NUMBER',
    macroName: 'VOUCHER_NUMBER',
    macroKey: 'VOUCHER_NUMBER',
    spId: 0,
    comments: 'VOUCHER_NUMBER',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'VOUCHER_NUMBER',
    valueScript: 'voucherNumberServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 20,
    macroScriptId: 20,
    macroCode: 'VOUCHER_VALID_DATE',
    macroName: 'VOUCHER_VALID_DATE',
    macroKey: 'VOUCHER_VALID_DATE',
    spId: 0,
    comments: 'VOUCHER_VALID_DATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'VOUCHER_VALID_DATE',
    valueScript: 'No need VOUCHER_VALID_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 21,
    macroScriptId: 21,
    macroCode: 'SysDate',
    macroName: 'SysDate',
    macroKey: 'SysDate',
    spId: 0,
    comments: 'SysDate',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'SYSDATE',
    valueScript: 'SELECT NOW()',
    scriptType: 'S',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 22,
    macroScriptId: 22,
    macroCode: 'ENCRIPT_ACC_NBR',
    macroName: 'ENCRIPT_ACC_NBR',
    macroKey: 'ENCRIPT_ACC_NBR',
    spId: 0,
    comments: 'ENCRIPT_ACC_NBR',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'ENCRIPT_ACC_NBR',
    valueScript: 'encriptAccNbrMsgParamServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 61,
    macroScriptId: 61,
    macroCode: 'TIME_RANGE_END',
    macroName: 'TIME_RANGE_END',
    macroKey: 'TIME_RANGE_END',
    spId: 0,
    comments: 'TIME_RANGE_END',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'TIME_RANGE_END',
    valueScript: 'No need TIME_RANGE_END script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 62,
    macroScriptId: 62,
    macroCode: 'FAILURE_THRESHOLD',
    macroName: 'FAILURE_THRESHOLD',
    macroKey: 'FAILURE_THRESHOLD',
    spId: 0,
    comments: 'FAILURE_THRESHOLD',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'FAILURE_THRESHOLD',
    valueScript: 'No need FAILURE_THRESHOLD script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 63,
    macroScriptId: 63,
    macroCode: 'ALARM_NAME',
    macroName: 'ALARM_NAME',
    macroKey: 'ALARM_NAME',
    spId: 0,
    comments: 'ALARM_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'ALARM_NAME',
    valueScript: 'No need ALARM_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 64,
    macroScriptId: 64,
    macroCode: 'TIME_RANGE_START',
    macroName: 'TIME_RANGE_START',
    macroKey: 'TIME_RANGE_START',
    spId: 0,
    comments: 'TIME_RANGE_START',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'TIME_RANGE_START',
    valueScript: 'No need TIME_RANGE_START script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 66,
    macroScriptId: 66,
    macroCode: 'CAMPAIGN_CODE',
    macroName: 'CAMPAIGN_CODE',
    macroKey: 'CAMPAIGN_CODE',
    spId: 0,
    comments: 'CAMPAIGN_CODE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CAMPAIGN_CODE',
    valueScript: 'CAMPAIGN_CODE',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 67,
    macroScriptId: 67,
    macroCode: 'CAMPAIGN_END_DATE',
    macroName: 'CAMPAIGN_END_DATE',
    macroKey: 'CAMPAIGN_END_DATE',
    spId: 0,
    comments: 'CAMPAIGN_END_DATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CAMPAIGN_END_DATE',
    valueScript: 'CAMPAIGN_END_DATE',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 68,
    macroScriptId: 68,
    macroCode: 'STAFF_NAME',
    macroName: 'STAFF_NAME',
    macroKey: 'STAFF_NAME',
    spId: 0,
    comments: 'STAFF_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'STAFF_NAME',
    valueScript: 'STAFF_NAME',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 121,
    macroScriptId: 121,
    macroCode: 'LAST_DAY_OF_MONTH',
    macroName: 'LAST_DAY_OF_MONTH',
    macroKey: 'LAST_DAY_OF_MONTH',
    spId: 0,
    comments: 'LAST_DAY_OF_MONTH',
    dataType: null,
    useScope: null,
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'LAST_DAY_OF_MONTH',
    valueScript: 'lastDayOfMonthParamServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: 'Y',
    adviceMacroScript: null,
  },
  {
    macroId: 122,
    macroScriptId: 122,
    macroCode: 'vasOfferName',
    macroName: 'vasOfferName',
    macroKey: 'vasOfferName',
    spId: 0,
    comments: 'vasOfferName',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'vasOfferName',
    valueScript: 'No need vasOfferName script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 123,
    macroScriptId: 123,
    macroCode: 'DAYS_TO_THE_LAST_DAY_OF_MONTH',
    macroName: 'DAYS_TO_THE_LAST_DAY_OF_MONTH',
    macroKey: 'DAYS_TO_THE_LAST_DAY_OF_MONTH',
    spId: 0,
    comments: 'DAYS_TO_THE_LAST_DAY_OF_MONTH',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'DAYS_TO_THE_LAST_DAY_OF_MONTH',
    valueScript: 'daysToLastDayOfMonthParamServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 124,
    macroScriptId: 124,
    macroCode: 'FORMAT_BONUS_VALUE',
    macroName: 'FORMAT_BONUS_VALUE',
    macroKey: 'FORMAT_BONUS_VALUE',
    spId: 0,
    comments: 'FORMAT_BONUS_VALUE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'FORMAT_BONUS_VALUE',
    valueScript: 'No need FORMAT_BONUS_VALUE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 125,
    macroScriptId: 125,
    macroCode: 'FORMAT_BONUS_UNIT',
    macroName: 'FORMAT_BONUS_UNIT',
    macroKey: 'FORMAT_BONUS_UNIT',
    spId: 0,
    comments: 'FORMAT_BONUS_UNIT',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'FORMAT_BONUS_UNIT',
    valueScript: 'No need FORMAT_BONUS_UNIT script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 126,
    macroScriptId: 126,
    macroCode: 'FILE_NAME',
    macroName: 'FILE_NAME',
    macroKey: 'FILE_NAME',
    spId: 0,
    comments: 'FILE_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'FILE_NAME',
    valueScript: 'FILE_NAME',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 127,
    macroScriptId: 127,
    macroCode: 'OPERATION_TIME',
    macroName: 'OPERATION_TIME',
    macroKey: 'OPERATION_TIME',
    spId: 0,
    comments: 'OPERATION_TIME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'OPERATION_TIME',
    valueScript: 'OPERATION_TIME',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 128,
    macroScriptId: 128,
    macroCode: 'FILE_DOWNLOAD_STATUS',
    macroName: 'FILE_DOWNLOAD_STATUS',
    macroKey: 'FILE_DOWNLOAD_STATUS',
    spId: 0,
    comments: 'FILE_DOWNLOAD_STATUS',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'FILE_DOWNLOAD_STATUS',
    valueScript: 'FILE_DOWNLOAD_STATUS',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 129,
    macroScriptId: 129,
    macroCode: 'OPER_STAFF_NAME',
    macroName: 'OPER_STAFF_NAME',
    macroKey: 'OPER_STAFF_NAME',
    spId: 0,
    comments: 'OPER_STAFF_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'OPER_STAFF_NAME',
    valueScript: 'OPER_STAFF_NAME',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 130,
    macroScriptId: 130,
    macroCode: 'FAIL_RATE',
    macroName: 'FAIL_RATE',
    macroKey: 'FAIL_RATE',
    spId: 0,
    comments: 'FAIL_RATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'FAIL_RATE',
    valueScript: 'FAIL_RATE',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 131,
    macroScriptId: 131,
    macroCode: 'PROCESS_TYPE_NAME',
    macroName: 'PROCESS_TYPE_NAME',
    macroKey: 'PROCESS_TYPE_NAME',
    spId: 0,
    comments: 'PROCESS_TYPE_NAME',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'PROCESS_TYPE_NAME',
    valueScript: 'PROCESS_TYPE_NAME',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 132,
    macroScriptId: 132,
    macroCode: 'APPROVE_OPERTION_TYPE',
    macroName: 'APPROVE_OPERTION_TYPE',
    macroKey: 'APPROVE_OPERTION_TYPE',
    spId: 0,
    comments: 'APPROVE_OPERTION_TYPE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'APPROVE_OPERTION_TYPE',
    valueScript: 'APPROVE_OPERTION_TYPE',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 133,
    macroScriptId: 133,
    macroCode: 'CMS_CREATIVE_CODE',
    macroName: 'CMS_CREATIVE_CODE',
    macroKey: 'CMS_CREATIVE_CODE',
    spId: 0,
    comments: 'CMS_CREATIVE_CODE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CMS_CREATIVE_CODE',
    valueScript: 'cmsCreativeCodeParamServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: 'Y',
    adviceMacroScript: null,
  },
  {
    macroId: 134,
    macroScriptId: 134,
    macroCode: 'LATEST_PROMO_INFO',
    macroName: 'LATEST_PROMO_INFO',
    macroKey: 'LATEST_PROMO_INFO',
    spId: 0,
    comments: 'LATEST_PROMO_INFO',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'LATEST_PROMO_INFO',
    valueScript: 'LATEST_PROMO_INFO',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: 'Y',
    adviceMacroScript: null,
  },
  {
    macroId: 135,
    macroScriptId: 135,
    macroCode: 'CMS_PAGE_TITLE',
    macroName: 'CMS_PAGE_TITLE',
    macroKey: 'CMS_PAGE_TITLE',
    spId: 0,
    comments: 'CMS_PAGE_TITLE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CMS_PAGE_TITLE',
    valueScript: 'cmsPageTitleParamServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: 'Y',
    adviceMacroScript: null,
  },
  {
    macroId: 136,
    macroScriptId: 136,
    macroCode: 'APP_SOURCE_CODE',
    macroName: 'APP_SOURCE_CODE',
    macroKey: 'APP_SOURCE_CODE',
    spId: 0,
    comments: 'APP_SOURCE_CODE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'APP_SOURCE_CODE',
    valueScript: 'No need APP_SOURCE_CODE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: 'Y',
    adviceMacroScript: null,
  },
  {
    macroId: 138,
    macroScriptId: 138,
    macroCode: 'SERVICE_NUMBER',
    macroName: 'SERVICE_NUMBER',
    macroKey: 'SERVICE_NUMBER',
    spId: 0,
    comments: 'SERVICE_NUMBER',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'SERVICE_NUMBER',
    valueScript: 'No need SERVICE_NUMBER script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 139,
    macroScriptId: 139,
    macroCode: 'CAMPAIGN_PRIORITY',
    macroName: 'CAMPAIGN_PRIORITY',
    macroKey: 'CAMPAIGN_PRIORITY',
    spId: 0,
    comments: 'CAMPAIGN_PRIORITY',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CAMPAIGN_PRIORITY',
    valueScript: 'No need CAMPAIGN_PRIORITY script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 140,
    macroScriptId: 140,
    macroCode: 'CAMPAIGN_CREATOR',
    macroName: 'CAMPAIGN_CREATOR',
    macroKey: 'CAMPAIGN_CREATOR',
    spId: 0,
    comments: 'CAMPAIGN_CREATOR',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CAMPAIGN_CREATOR',
    valueScript: 'No need CAMPAIGN_CREATOR script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 141,
    macroScriptId: 141,
    macroCode: 'CAMPAIGN_PREV_AUDITOR',
    macroName: 'CAMPAIGN_PREV_AUDITOR',
    macroKey: 'CAMPAIGN_PREV_AUDITOR',
    spId: 0,
    comments: 'CAMPAIGN_PREV_AUDITOR',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CAMPAIGN_PREV_AUDITOR',
    valueScript: 'No need CAMPAIGN_PREV_AUDITOR script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 142,
    macroScriptId: 142,
    macroCode: 'CAMPAIGN_AUDITOR',
    macroName: 'CAMPAIGN_AUDITOR',
    macroKey: 'CAMPAIGN_AUDITOR',
    spId: 0,
    comments: 'CAMPAIGN_AUDITOR',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CAMPAIGN_AUDITOR',
    valueScript: 'No need CAMPAIGN_AUDITOR script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 143,
    macroScriptId: 143,
    macroCode: 'APPROVAL_REMARKS',
    macroName: 'APPROVAL_REMARKS',
    macroKey: 'APPROVAL_REMARKS',
    spId: 0,
    comments: 'APPROVAL_REMARKS',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'APPROVAL_REMARKS',
    valueScript: 'No need APPROVAL_REMARKS script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 144,
    macroScriptId: 144,
    macroCode: 'purchaseOfferCode',
    macroName: 'purchaseOfferCode',
    macroKey: 'purchaseOfferCode',
    spId: 0,
    comments: 'purchaseOfferCode',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'purchaseOfferCode',
    valueScript: 'No need purchaseOfferCode script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 145,
    macroScriptId: 145,
    macroCode: 'mobileNumber',
    macroName: 'mobileNumber',
    macroKey: 'mobileNumber',
    spId: 0,
    comments: 'mobileNumber',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'mobileNumber',
    valueScript: 'No need mobileNumber script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 146,
    macroScriptId: 146,
    macroCode: 'amount',
    macroName: 'amount',
    macroKey: 'amount',
    spId: 0,
    comments: 'amount',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'amount',
    valueScript: 'No need amount script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 147,
    macroScriptId: 147,
    macroCode: 'accNbr',
    macroName: 'accNbr',
    macroKey: 'accNbr',
    spId: 0,
    comments: 'accNbr',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'accNbr',
    valueScript: 'No need accNbr script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 148,
    macroScriptId: 148,
    macroCode: 'EMAIL_TRACK',
    macroName: 'EMAIL_TRACK',
    macroKey: 'EMAIL_TRACK',
    spId: 0,
    comments: 'EMAIL_TRACK',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'EMAIL_TRACK',
    valueScript: 'emailTrackParamSerivceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 149,
    macroScriptId: 149,
    macroCode: 'UTM_LINK',
    macroName: 'UTM_LINK',
    macroKey: 'UTM_LINK',
    spId: 0,
    comments: 'UTM_LINK',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'UTM_LINK',
    valueScript: 'utmLinkParamServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: 'Y',
    adviceMacroScript: null,
  },
  {
    macroId: 150,
    macroScriptId: 150,
    macroCode: 'OTP_CODE',
    macroName: 'OTP_CODE',
    macroKey: 'OTP_CODE',
    spId: 0,
    comments: 'OTP_CODE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'OTP_CODE',
    valueScript: 'No need OTP_CODE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 151,
    macroScriptId: 151,
    macroCode: 'BONUS_LIST',
    macroName: 'BONUS_LIST',
    macroKey: 'BONUS_LIST',
    spId: 0,
    comments: 'BONUS_LIST',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'BONUS_LIST',
    valueScript: 'No need BONUS_LIST script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 152,
    macroScriptId: 152,
    macroCode: 'BONUS_FIXED_EXP_DATE',
    macroName: 'BONUS_FIXED_EXP_DATE',
    macroKey: 'BONUS_FIXED_EXP_DATE',
    spId: 0,
    comments: 'BONUS_FIXED_EXP_DATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'BONUS_FIXED_EXP_DATE',
    valueScript: 'No need BONUS_FIXED_EXP_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 153,
    macroScriptId: 153,
    macroCode: 'BONUS_RELATIVE_EXP_DATE_VALUE',
    macroName: 'BONUS_RELATIVE_EXP_DATE_VALUE',
    macroKey: 'BONUS_RELATIVE_EXP_DATE_VALUE',
    spId: 0,
    comments: 'BONUS_RELATIVE_EXP_DATE_VALUE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'BONUS_RELATIVE_EXP_DATE_VALUE',
    valueScript: 'No need BONUS_RELATIVE_EXP_DATE_VALUE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 154,
    macroScriptId: 154,
    macroCode: 'BONUS_RELATIVE_EXP_DATE_UNIT',
    macroName: 'BONUS_RELATIVE_EXP_DATE_UNIT',
    macroKey: 'BONUS_RELATIVE_EXP_DATE_UNIT',
    spId: 0,
    comments: 'BONUS_RELATIVE_EXP_DATE_UNIT',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'BONUS_RELATIVE_EXP_DATE_UNIT',
    valueScript: 'No need BONUS_RELATIVE_EXP_DATE_UNIT script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 155,
    macroScriptId: 155,
    macroCode: 'OFFER_LIST',
    macroName: 'OFFER_LIST',
    macroKey: 'OFFER_LIST',
    spId: 0,
    comments: 'OFFER_LIST: Array(offerName, originPrice, salesPrice)',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'OFFER_LIST',
    valueScript: 'No need OFFER_LIST script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 156,
    macroScriptId: 156,
    macroCode: 'NOTIFY_CONTACT_ID',
    macroName: 'NOTIFY_CONTACT_ID',
    macroKey: 'NOTIFY_CONTACT_ID',
    spId: 0,
    comments: 'NOTIFY_CONTACT_ID',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'NOTIFY_CONTACT_ID',
    valueScript: 'No need NOTIFY_CONTACT_ID script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 157,
    macroScriptId: 157,
    macroCode: 'ORDER_RET_CODE',
    macroName: 'ORDER_RET_CODE',
    macroKey: 'ORDER_RET_CODE',
    spId: 0,
    comments: 'ORDER_RET_CODE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'ORDER_RET_CODE',
    valueScript: 'No need ORDER_RET_CODE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 158,
    macroScriptId: 158,
    macroCode: 'CRM_ORDER_ID',
    macroName: 'CRM_ORDER_ID',
    macroKey: 'CRM_ORDER_ID',
    spId: 0,
    comments: 'CRM_ORDER_ID',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'CRM_ORDER_ID',
    valueScript: 'No need CRM_ORDER_ID script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 159,
    macroScriptId: 159,
    macroCode: 'VOUCHER_CODE',
    macroName: 'VOUCHER_CODE',
    macroKey: 'VOUCHER_CODE',
    spId: 0,
    comments: 'VOUCHER_CODE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'VOUCHER_CODE',
    valueScript: 'No need VOUCHER_CODE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 160,
    macroScriptId: 160,
    macroCode: 'LOTTERY_CHANCE',
    macroName: 'LOTTERY_CHANCE',
    macroKey: 'LOTTERY_CHANCE',
    spId: 0,
    comments: 'LOTTERY_CHANCE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'LOTTERY_CHANCE',
    valueScript: 'No need LOTTERY_CHANCE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 161,
    macroScriptId: 161,
    macroCode: 'PERCENTAGE',
    macroName: 'PERCENTAGE',
    macroKey: 'PERCENTAGE',
    spId: 0,
    comments: 'PERCENTAGE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'PERCENTAGE',
    valueScript: 'No need PERCENTAGE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 162,
    macroScriptId: 162,
    macroCode: 'OFFERS',
    macroName: 'OFFERS',
    macroKey: 'OFFERS',
    spId: 0,
    comments: 'OFFERS',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'OFFERS',
    valueScript: 'offersMacrosServiceImpl',
    scriptType: 'B',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 163,
    macroScriptId: 163,
    macroCode: 'ACC_BALANCE',
    macroName: 'ACC_BALANCE',
    macroKey: 'ACC_BALANCE',
    spId: 0,
    comments: 'ACC_BALANCE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'ACC_BALANCE',
    valueScript: 'No need ACC_BALANCE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 164,
    macroScriptId: 164,
    macroCode: 'ACC_EXP_DATE',
    macroName: 'ACC_EXP_DATE',
    macroKey: 'ACC_EXP_DATE',
    spId: 0,
    comments: 'ACC_EXP_DATE',
    dataType: null,
    useScope: 'MCCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'ACC_EXP_DATE',
    valueScript: 'No need ACC_EXP_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1011,
    macroScriptId: 1011,
    macroCode: 'orderNbr',
    macroName: 'orderNbr',
    macroKey: 'orderNbr',
    spId: null,
    comments: 'orderNbr',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orderNbr',
    valueScript: 'orderNbr',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1012,
    macroScriptId: 1012,
    macroCode: 'workOrderResultName',
    macroName: 'workOrderResultName',
    macroKey: 'workOrderResultName',
    spId: null,
    comments: 'workOrderResultName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'workOrderResultName',
    valueScript: 'workOrderResultName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1013,
    macroScriptId: 1013,
    macroCode: 'staffEmail',
    macroName: 'staffEmail',
    macroKey: 'staffEmail',
    spId: null,
    comments: 'staffEmail',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'staffEmail',
    valueScript: 'staffEmail',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1014,
    macroScriptId: 1014,
    macroCode: 'dPartyCode',
    macroName: 'dPartyCode',
    macroKey: 'dPartyCode',
    spId: null,
    comments: 'dPartyCode',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'dPartyCode',
    valueScript: 'dPartyCode',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1015,
    macroScriptId: 1015,
    macroCode: 'lastApprovalDate',
    macroName: 'lastApprovalDate',
    macroKey: 'lastApprovalDate',
    spId: null,
    comments: 'lastApprovalDate',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'lastApprovalDate',
    valueScript: 'lastApprovalDate',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1016,
    macroScriptId: 1016,
    macroCode: 'triggerTime',
    macroName: 'triggerTime',
    macroKey: 'triggerTime',
    spId: null,
    comments: 'triggerTime',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'triggerTime',
    valueScript: 'triggerTime',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1017,
    macroScriptId: 1017,
    macroCode: 'parentOrgName',
    macroName: 'parentOrgName',
    macroKey: 'parentOrgName',
    spId: null,
    comments: 'parentOrgName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'parentOrgName',
    valueScript: 'parentOrgName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1018,
    macroScriptId: 1018,
    macroCode: 'emailAddress',
    macroName: 'emailAddress',
    macroKey: 'emailAddress',
    spId: null,
    comments: 'emailAddress',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'emailAddress',
    valueScript: 'emailAddress',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1019,
    macroScriptId: 1019,
    macroCode: 'orgChannelCategoryName',
    macroName: 'orgChannelCategoryName',
    macroKey: 'orgChannelCategoryName',
    spId: null,
    comments: 'orgChannelCategoryName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgChannelCategoryName',
    valueScript: 'orgChannelCategoryName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1020,
    macroScriptId: 1020,
    macroCode: 'regNum',
    macroName: 'regNum',
    macroKey: 'regNum',
    spId: null,
    comments: 'regNum',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'regNum',
    valueScript: 'regNum',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1021,
    macroScriptId: 1021,
    macroCode: 'orgRegNum',
    macroName: 'orgRegNum',
    macroKey: 'orgRegNum',
    spId: null,
    comments: 'orgRegNum',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgRegNum',
    valueScript: 'orgRegNum',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1022,
    macroScriptId: 1022,
    macroCode: 'orgCode',
    macroName: 'orgCode',
    macroKey: 'orgCode',
    spId: null,
    comments: 'orgCode',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgCode',
    valueScript: 'orgCode',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1023,
    macroScriptId: 1023,
    macroCode: 'staffName',
    macroName: 'staffName',
    macroKey: 'staffName',
    spId: null,
    comments: 'staffName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'staffName',
    valueScript: 'staffName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1024,
    macroScriptId: 1024,
    macroCode: 'fullRegionName',
    macroName: 'fullRegionName',
    macroKey: 'fullRegionName',
    spId: null,
    comments: 'fullRegionName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'fullRegionName',
    valueScript: 'fullRegionName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1025,
    macroScriptId: 1025,
    macroCode: 'orderCreatedDate',
    macroName: 'orderCreatedDate',
    macroKey: 'orderCreatedDate',
    spId: null,
    comments: 'orderCreatedDate',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orderCreatedDate',
    valueScript: 'orderCreatedDate',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1026,
    macroScriptId: 1026,
    macroCode: 'orderStateDate',
    macroName: 'orderStateDate',
    macroKey: 'orderStateDate',
    spId: null,
    comments: 'orderStateDate',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orderStateDate',
    valueScript: 'orderStateDate',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1027,
    macroScriptId: 1027,
    macroCode: 'orgName',
    macroName: 'orgName',
    macroKey: 'orgName',
    spId: null,
    comments: 'orgName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgName',
    valueScript: 'orgName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1028,
    macroScriptId: 1028,
    macroCode: 'orgLegalCertNbr',
    macroName: 'orgLegalCertNbr',
    macroKey: 'orgLegalCertNbr',
    spId: null,
    comments: 'orgLegalCertNbr',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgLegalCertNbr',
    valueScript: 'orgLegalCertNbr',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1029,
    macroScriptId: 1029,
    macroCode: 'staffCode',
    macroName: 'staffCode',
    macroKey: 'staffCode',
    spId: null,
    comments: 'staffCode',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'staffCode',
    valueScript: 'staffCode',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1030,
    macroScriptId: 1030,
    macroCode: 'orgSubtype',
    macroName: 'orgSubtype',
    macroKey: 'orgSubtype',
    spId: null,
    comments: 'orgSubtype',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgSubtype',
    valueScript: 'orgSubtype',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1031,
    macroScriptId: 1031,
    macroCode: 'orgChannelType',
    macroName: 'orgChannelType',
    macroKey: 'orgChannelType',
    spId: null,
    comments: 'orgChannelType',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgChannelType',
    valueScript: 'orgChannelType',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1032,
    macroScriptId: 1032,
    macroCode: 'level',
    macroName: 'level',
    macroKey: 'level',
    spId: null,
    comments: 'level',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'level',
    valueScript: 'level',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1033,
    macroScriptId: 1033,
    macroCode: 'dPartyName',
    macroName: 'dPartyName',
    macroKey: 'dPartyName',
    spId: null,
    comments: 'dPartyName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'dPartyName',
    valueScript: 'dPartyName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1034,
    macroScriptId: 1034,
    macroCode: 'notifyTime',
    macroName: 'notifyTime',
    macroKey: 'notifyTime',
    spId: null,
    comments: 'notifyTime',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'notifyTime',
    valueScript: 'notifyTime',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1035,
    macroScriptId: 1035,
    macroCode: 'sPartyName',
    macroName: 'sPartyName',
    macroKey: 'sPartyName',
    spId: null,
    comments: 'sPartyName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'sPartyName',
    valueScript: 'sPartyName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1036,
    macroScriptId: 1036,
    macroCode: 'orgLegalCertType',
    macroName: 'orgLegalCertType',
    macroKey: 'orgLegalCertType',
    spId: null,
    comments: 'orgLegalCertType',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgLegalCertType',
    valueScript: 'orgLegalCertType',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1037,
    macroScriptId: 1037,
    macroCode: 'notificationEmail',
    macroName: 'notificationEmail',
    macroKey: 'notificationEmail',
    spId: null,
    comments: 'notificationEmail',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'notificationEmail',
    valueScript: 'notificationEmail',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1038,
    macroScriptId: 1038,
    macroCode: 'orderPartyName',
    macroName: 'orderPartyName',
    macroKey: 'orderPartyName',
    spId: null,
    comments: 'orderPartyName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orderPartyName',
    valueScript: 'orderPartyName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1039,
    macroScriptId: 1039,
    macroCode: 'orgSubtypeName',
    macroName: 'orgSubtypeName',
    macroKey: 'orgSubtypeName',
    spId: null,
    comments: 'orgSubtypeName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgSubtypeName',
    valueScript: 'orgSubtypeName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1040,
    macroScriptId: 1040,
    macroCode: 'orderEventName',
    macroName: 'orderEventName',
    macroKey: 'orderEventName',
    spId: null,
    comments: 'orderEventName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orderEventName',
    valueScript: 'orderEventName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1041,
    macroScriptId: 1041,
    macroCode: 'approveOrRejectDate',
    macroName: 'approveOrRejectDate',
    macroKey: 'approveOrRejectDate',
    spId: null,
    comments: 'approveOrRejectDate',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'approveOrRejectDate',
    valueScript: 'approveOrRejectDate',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1042,
    macroScriptId: 1042,
    macroCode: 'orgChannelTypeName',
    macroName: 'orgChannelTypeName',
    macroKey: 'orgChannelTypeName',
    spId: null,
    comments: 'orgChannelTypeName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orgChannelTypeName',
    valueScript: 'orgChannelTypeName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1043,
    macroScriptId: 1043,
    macroCode: 'partnerPassword',
    macroName: 'partnerPassword',
    macroKey: 'partnerPassword',
    spId: null,
    comments: 'partnerPassword',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'partnerPassword',
    valueScript: 'partnerPassword',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1044,
    macroScriptId: 1044,
    macroCode: 'eventTypeName',
    macroName: 'eventTypeName',
    macroKey: 'eventTypeName',
    spId: null,
    comments: 'eventTypeName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'eventTypeName',
    valueScript: 'eventTypeName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1045,
    macroScriptId: 1045,
    macroCode: 'channelCategoryName',
    macroName: 'channelCategoryName',
    macroKey: 'channelCategoryName',
    spId: null,
    comments: 'channelCategoryName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'channelCategoryName',
    valueScript: 'channelCategoryName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1046,
    macroScriptId: 1046,
    macroCode: 'staffMobileNumber',
    macroName: 'staffMobileNumber',
    macroKey: 'staffMobileNumber',
    spId: null,
    comments: 'staffMobileNumber',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'staffMobileNumber',
    valueScript: 'staffMobileNumber',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1047,
    macroScriptId: 1047,
    macroCode: 'orderStateName',
    macroName: 'orderStateName',
    macroKey: 'orderStateName',
    spId: null,
    comments: 'orderStateName',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orderStateName',
    valueScript: 'orderStateName',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1048,
    macroScriptId: 1048,
    macroCode: 'ApprovalNotes',
    macroName: 'ApprovalNotes',
    macroKey: 'ApprovalNotes',
    spId: null,
    comments: 'ApprovalNotes',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'ApprovalNotes',
    valueScript: 'ApprovalNotes',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 1049,
    macroScriptId: 1049,
    macroCode: 'orderComments',
    macroName: 'orderComments',
    macroKey: 'orderComments',
    spId: null,
    comments: 'orderComments',
    dataType: null,
    useScope: 'DSCM',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'orderComments',
    valueScript: 'orderComments',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2001,
    macroScriptId: 2001,
    macroCode: 'REWARD_TYPE',
    macroName: 'REWARD_TYPE',
    macroKey: 'REWARD_TYPE',
    spId: 0,
    comments: 'REWARD_TYPE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'REWARD_TYPE',
    valueScript: 'REWARD_TYPE',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2002,
    macroScriptId: 2002,
    macroCode: 'REWARD_CODE',
    macroName: 'REWARD_CODE',
    macroKey: 'REWARD_CODE',
    spId: 0,
    comments: 'REWARD_CODE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: 0,
    macroLength: null,
    appChannelId: null,
    scriptName: 'REWARD_CODE',
    valueScript: 'REWARD_CODE',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2003,
    macroScriptId: 2003,
    macroCode: 'SHARER_REWARD_NAME',
    macroName: 'SHARER_REWARD_NAME',
    macroKey: 'SHARER_REWARD_NAME',
    spId: null,
    comments: 'SHARER_REWARD_NAME',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'SHARER_REWARD_NAME',
    valueScript: 'No need SHARER_REWARD_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2004,
    macroScriptId: 2004,
    macroCode: 'SHARED_REWARD_NAME',
    macroName: 'SHARED_REWARD_NAME',
    macroKey: 'SHARED_REWARD_NAME',
    spId: null,
    comments: 'SHARED_REWARD_NAME',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'SHARED_REWARD_NAME',
    valueScript: 'No need SHARED_REWARD_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2005,
    macroScriptId: 2005,
    macroCode: 'LUCKY_DRAW_NAME',
    macroName: 'LUCKY_DRAW_NAME',
    macroKey: 'LUCKY_DRAW_NAME',
    spId: null,
    comments: 'LUCKY_DRAW_NAME',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'LUCKY_DRAW_NAME',
    valueScript: 'No need LUCKY_DRAW_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2006,
    macroScriptId: 2006,
    macroCode: 'PRC_RES_EXP_DATE',
    macroName: 'PRC_RES_EXP_DATE',
    macroKey: 'PRC_RES_EXP_DATE',
    spId: null,
    comments: 'PRC_RES_EXP_DATE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'PRC_RES_EXP_DATE',
    valueScript: 'No need PRC_RES_EXP_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2007,
    macroScriptId: 2007,
    macroCode: 'PRC_RES_PWD',
    macroName: 'PRC_RES_PWD',
    macroKey: 'PRC_RES_PWD',
    spId: null,
    comments: 'PRC_RES_PWD',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'PRC_RES_PWD',
    valueScript: 'No need PRC_RES_PWD script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2008,
    macroScriptId: 2008,
    macroCode: 'PRC_RES_SN',
    macroName: 'PRC_RES_SN',
    macroKey: 'PRC_RES_SN',
    spId: null,
    comments: 'PRC_RES_SN',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'PRC_RES_SN',
    valueScript: 'No need PRC_RES_SN script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2009,
    macroScriptId: 2009,
    macroCode: 'VALID_DAYS',
    macroName: 'VALID_DAYS',
    macroKey: 'VALID_DAYS',
    spId: null,
    comments: 'VALID_DAYS',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'VALID_DAYS',
    valueScript: 'No need VALID_DAYS script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2010,
    macroScriptId: 2010,
    macroCode: 'QUANTITY',
    macroName: 'QUANTITY',
    macroKey: 'QUANTITY',
    spId: null,
    comments: 'QUANTITY',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'QUANTITY',
    valueScript: 'No need QUANTITY script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2011,
    macroScriptId: 2011,
    macroCode: 'EXP_DATE',
    macroName: 'EXP_DATE',
    macroKey: 'EXP_DATE',
    spId: null,
    comments: 'EXP_DATE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'EXP_DATE',
    valueScript: 'No need EXP_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2012,
    macroScriptId: 2012,
    macroCode: 'REWARD_NAME',
    macroName: 'REWARD_NAME',
    macroKey: 'REWARD_NAME',
    spId: 0,
    comments: 'REWARD_NAME',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'REWARD_NAME',
    valueScript: 'No need REWARD_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2013,
    macroScriptId: 2013,
    macroCode: 'MY_PRIZES_LINK',
    macroName: 'MY_PRIZES_LINK',
    macroKey: 'MY_PRIZES_LINK',
    spId: 0,
    comments: 'MY_PRIZES_LINK',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'MY_PRIZES_LINK',
    valueScript: 'No need MY_PRIZES_LINK script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2014,
    macroScriptId: 2014,
    macroCode: 'DATE_UNIT',
    macroName: 'DATE_UNIT',
    macroKey: 'DATE_UNIT',
    spId: 0,
    comments: 'DATE_UNIT',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'DATE_UNIT',
    valueScript: 'No need DATE_UNIT script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2015,
    macroScriptId: 2015,
    macroCode: 'MY_PRIZES_LINK_INBOX',
    macroName: 'MY_PRIZES_LINK_INBOX',
    macroKey: 'MY_PRIZES_LINK_INBOX',
    spId: 0,
    comments: 'MY_PRIZES_LINK_INBOX',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'MY_PRIZES_LINK_INBOX',
    valueScript: 'No need MY_PRIZES_LINK_INBOX script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2016,
    macroScriptId: 2016,
    macroCode: 'RECEIVE_DEAD_DATE',
    macroName: 'RECEIVE_DEAD_DATE',
    macroKey: 'RECEIVE_DEAD_DATE',
    spId: 0,
    comments: 'RECEIVE_DEAD_DATE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'RECEIVE_DEAD_DATE',
    valueScript: 'No need RECEIVE_DEAD_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2017,
    macroScriptId: 2017,
    macroCode: 'LUCKY_DRAW_EFF_DATE',
    macroName: 'LUCKY_DRAW_EFF_DATE',
    macroKey: 'LUCKY_DRAW_EFF_DATE',
    spId: 0,
    comments: 'LUCKY_DRAW_EFF_DATE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'LUCKY_DRAW_EFF_DATE',
    valueScript: 'No need LUCKY_DRAW_EFF_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2018,
    macroScriptId: 2018,
    macroCode: 'LUCKY_DRAW_EXP_DATE',
    macroName: 'LUCKY_DRAW_EXP_DATE',
    macroKey: 'LUCKY_DRAW_EXP_DATE',
    spId: 0,
    comments: 'LUCKY_DRAW_EXP_DATE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'LUCKY_DRAW_EXP_DATE',
    valueScript: 'No need LUCKY_DRAW_EXP_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2019,
    macroScriptId: 2019,
    macroCode: 'USER_NAME',
    macroName: 'USER_NAME',
    macroKey: 'USER_NAME',
    spId: 0,
    comments: 'USER_NAME',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'USER_NAME',
    valueScript: 'No need USER_NAME script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2020,
    macroScriptId: 2020,
    macroCode: 'TO_MSISDN',
    macroName: 'TO_MSISDN',
    macroKey: 'TO_MSISDN',
    spId: 0,
    comments: 'TO_MSISDN',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'TO_MSISDN',
    valueScript: 'No need TO_MSISDN script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2021,
    macroScriptId: 2021,
    macroCode: 'COUPON_CODE',
    macroName: 'COUPON_CODE',
    macroKey: 'COUPON_CODE',
    spId: 0,
    comments: 'COUPON_CODE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'COUPON_CODE',
    valueScript: 'No need COUPON_CODE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2022,
    macroScriptId: 2022,
    macroCode: 'COUPON_EFF_DATE',
    macroName: 'COUPON_EFF_DATE',
    macroKey: 'COUPON_EFF_DATE',
    spId: 0,
    comments: 'COUPON_EFF_DATE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'COUPON_EFF_DATE',
    valueScript: 'No need COUPON_EFF_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 2023,
    macroScriptId: 2023,
    macroCode: 'COUPON_EXP_DATE',
    macroName: 'COUPON_EXP_DATE',
    macroKey: 'COUPON_EXP_DATE',
    spId: 0,
    comments: 'COUPON_EXP_DATE',
    dataType: null,
    useScope: 'GCP',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'COUPON_EXP_DATE',
    valueScript: 'No need COUPON_EXP_DATE script',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
  {
    macroId: 6001,
    macroScriptId: 6001,
    macroCode: 'REPORT_EMAIL_CONTENT',
    macroName: 'REPORT_EMAIL_CONTENT',
    macroKey: 'REPORT_EMAIL_CONTENT',
    spId: 0,
    comments: 'REPORT_EMAIL_CONTENT',
    dataType: null,
    useScope: 'CEE',
    comAcctId: null,
    macroLength: null,
    appChannelId: null,
    scriptName: 'REPORT_EMAIL_CONTENT',
    valueScript: 'REPORT_EMAIL_CONTENT',
    scriptType: 'P',
    macroTemplate: null,
    testParam: null,
    hasParam: null,
    adviceMacroScript: null,
  },
];
let tagItem = [
  {
    labelCode: 'tag0923',
    labelName: 'tag0923',
    labelValueType: '1000',
    labelDataType: '1200',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'cccc',
    labelName: 'cccc',
    labelValueType: '1000',
    labelDataType: '1200',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'dudu_time4',
    labelName: 'dudu_time4',
    labelValueType: '1000',
    labelDataType: '1100',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'order_time3',
    labelName: 'order_time3',
    labelValueType: '1000',
    labelDataType: '1100',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
];
let profileItem = [
  {
    labelCode: 'acc_nbr',
    labelName: 'Service Number',
    labelValueType: '1000',
    labelDataType: '1200',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'acc_nbr_2',
    labelName: 'Service Number2',
    labelValueType: '1000',
    labelDataType: '1200',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'cust_id_2',
    labelName: 'Customer ID2',
    labelValueType: '1000',
    labelDataType: '1200',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'active_date_2',
    labelName: 'Activation Date2',
    labelValueType: '1000',
    labelDataType: '1100',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'cust_name_2',
    labelName: 'Customer Name2',
    labelValueType: '1000',
    labelDataType: '1200',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
  {
    labelCode: 'email_2',
    labelName: 'Email2',
    labelValueType: '1000',
    labelDataType: '1200',
    labelId: null,
    tableCode: null,
    enumValues: null,
  },
];

// 插入宏和变量
// eslint-disable-next-line @typescript-eslint/no-unused-vars
/* const MacroSelect = (props) => {
  const { editor } = props?.editorProps;
  const { state, view } = editor?.current || {};
  const handle = (v) => {
    if (!state || !view) return;
    const lineInfo = view.state.doc;
    const from = view.state.selection.main?.from;
    view.dispatch({
      changes: {
        from,
        insert: `$\{${v}}`,
      },
      selection: { anchor: lineInfo?.length + v?.length + 1 },
    });
  };
  return (
    <>
      <TextField
        select
        size="small"
        variant="standard"
        label={null}
        value="init"
        onChange={(ev) => {
          const v = ev.target.value;
          handle(v);
        }}
      >
        <MenuItem value="init" label="Macro Variables">Macro</MenuItem>
        <MenuItem value="START_DATE">START_DATE</MenuItem>
        <MenuItem value="END_DATE">END_DATE</MenuItem>
      </TextField>
    </>
  );
};
 */

// 查询宏变量
// eslint-disable-next-line consistent-return
async function qryMacroList(params): Promise {
  try {
    const response = await request('/ceg/ceg/AdviceMacroController/qryMacroList', {
      method: 'post',
      data: params,
    });
    if (response) {
      return response;
    }
  } catch (error) {
    return null;
  }
}
// 查询 User Tag变量 http://172.16.25.133/ceg/ceg/marketmgr/labelMgr/MccLabelGrpController/getLabelList

// eslint-disable-next-line consistent-return
async function qryTagList(params): Promise {
  try {
    const response = await request('/ceg/ceg/marketmgr/labelMgr/MccLabelGrpController/getLabelList', {
      method: 'post',
      data: params,
    });
    if (response) {
      return response;
    }
  } catch (error) {
    return null;
  }
}
// 查询 User Profile http://172.16.25.133/ceg/ceg/marketmgr/labelMgr/MccLabelGrpController/getProfileList

// eslint-disable-next-line consistent-return
async function qryProfileList(params): Promise {
  try {
    const response = await request('/ceg/ceg/marketmgr/labelMgr/MccLabelGrpController/getProfileList', {
      method: 'post',
      data: params,
    });
    if (response) {
      return response;
    }
  } catch (error) {
    return null;
  }
}

qryMacroList({}).then((data) => {
  if (data?.svcCont?.data) {
    macroItem = data?.svcCont?.data;
  }
});

qryTagList({ labelName: '', labelType: 'R' }).then((data) => {
  if (data?.svcCont?.data) {
    tagItem = data?.svcCont?.data;
  }
});
//  {item.paramName || item.labelName}
qryProfileList({ paramName: '' }).then((data) => {
  if (data?.svcCont?.data?.labelList) {
    profileItem = data?.svcCont?.data?.labelList;
  }
});

// 插入宏和变量
const MacroTabs = (props) => {
  const [anchorElement, setAnchorElement] = useState(null);
  const { editor } = props?.editorProps;
  const { state, view } = editor?.current || {};

  const groupedData = (macroItem || []).reduce((acc, item) => {
    if (item.useScope !== null) {
      if (!acc[item.useScope]) {
        acc[item.useScope] = {
          key: `group-${item.useScope}`,
          caption: item.useScope,
          subMenuItems: [],
        };
      }
      acc[item.useScope].subMenuItems.push({
        ...item,
        key: item.macroId.toString(),
        caption: item.macroName,
        // onClick: () => {} // 这里可以定义点击事件
      });
    }
    return acc;
  }, {});

  const finalData = Object.values(groupedData).map((group) => ({
    key: group.key,
    caption: group.caption,
    subMenuItems: group.subMenuItems.map((subItem) => ({
      ...subItem,
      key: subItem.key,
      caption: subItem.caption,
      // onClick: subItem.onClick
    })),
  }));

  const handle = (v) => {
    if (!state || !view) return;
    // const lineInfo = view.state.doc.lineAt(view.state.selection.main.from);
    const lineInfo = view.state.doc;
    const from = view.state.selection.main?.from;
    view.dispatch({
      changes: {
        from,
        // to: lineInfo.to,
        insert: `$\{${v}}`,
      },
      // selection: EditorSelection.range(lineInfo.from + mark.length, lineInfo.to),
      selection: { anchor: lineInfo?.length + v?.length + 2 },
    });
  };

  const handleClick = (event) => {
    setAnchorElement(event?.currentTarget);
  };
  const handleClose = (event) => {
    setAnchorElement(null);
  };

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  // const handleChange = (event, newValue) => {
  // };

  return (
    <>
      <Tooltip
        open={Boolean(anchorElement)}
        placement="bottom-start"
        classes={{ popper: 'CEEMacroTooltip' }}
        title={
          <CascadingMenu
            anchorElement={anchorElement}
            anchorOrigin={{
              vertical: 'top',
              horizontal: 'right',
            }}
            rootmenu="macroSelect"
            menuItems={finalData || []}
            tagItem={tagItem || []}
            profileItem={profileItem || []}
            onClose={handleClose}
            onClick={handle}
            open={Boolean(anchorElement)}
            transformOrigin={{
              vertical: 'top',
              horizontal: 'right',
            }}
          />
        }
      >
        <IconButton aria-label="Macro" aria-controls="user-menu" aria-haspopup="true" onClick={handleClick}>
          <svg fill="#005AF0" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <title>Macro</title>
            <path d="M12 0c6.628 0 12 5.373 12 12s-5.372 12-12 12C5.373 24 0 18.627 0 12S5.373 0 12 0zm-.92 19.278l5.034-8.377a.444.444 0 00.097-.268.455.455 0 00-.455-.455l-2.851.004.924-5.468-.927-.003-5.018 8.367s-.1.183-.1.291c0 .251.204.455.455.455l2.831-.004-.901 5.458z" />
          </svg>
        </IconButton>
      </Tooltip>
    </>
  );
};

const macro = {
  name: 'macro',
  keyCommand: 'macro',
  title: null,
  // button: { 'aria-label': 'Add macro text' },

  // 下拉形式
  // button: (command, props, opts) => <MacroSelect command={command} editorProps={{ ...props, ...opts }} />,

  // 级联选择形式
  button: (command, props, opts) => <MacroTabs command={command} editorProps={{ ...props, ...opts }} />,
  icon: (
    <svg fill="#005AF0" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <title>AMP</title>
      <path d="M12 0c6.628 0 12 5.373 12 12s-5.372 12-12 12C5.373 24 0 18.627 0 12S5.373 0 12 0zm-.92 19.278l5.034-8.377a.444.444 0 00.097-.268.455.455 0 00-.455-.455l-2.851.004.924-5.468-.927-.003-5.018 8.367s-.1.183-.1.291c0 .251.204.455.455.455l2.831-.004-.901 5.458z" />
    </svg>
  ),
  execute: ({ editor, state, view }) => {
    if (!state || !view) return;
    const lineInfo = view.state.doc.lineAt(view.state.selection.main.from);
    let mark = '#';
    const matchMark = lineInfo.text.match(/^#+/);
    if (matchMark && matchMark[0]) {
      const txt = matchMark[0];
      if (txt.length < 6) {
        mark = `${txt}#`;
      }
    }
    if (mark.length > 6) {
      mark = '#';
    }
    const title = lineInfo.text.replace(/^#+/, '');
    view.dispatch({
      changes: {
        from: lineInfo.from,
        to: lineInfo.to,
        insert: ` ${title}${mark}`,
      },
      // selection: EditorSelection.range(lineInfo.from + mark.length, lineInfo.to),
      selection: { anchor: lineInfo.from + mark.length },
    });
  },
};

export default function TextSidebarPanel({ data, setData }: TextSidebarPanelProps) {
  const [, setErrors] = useState<Zod.ZodError | null>(null);
  const updateData = (d: unknown) => {
    const res = TextPropsSchema.safeParse(d);
    if (res.success) {
      setData(res.data);
      setErrors(null);
    } else {
      setErrors(res.error);
    }
  };
  const enableMarkdown = data?.props?.markdown;
  document.documentElement.setAttribute('data-color-mode', 'light');

  return (
    <BaseSidebarPanel title="Text block">
      {!enableMarkdown ? (
        <TextInput
          label="Content"
          rows={5}
          defaultValue={data.props?.text ?? ''}
          onChange={(text) => updateData({ ...data, props: { ...data.props, text } })}
        />
      ) : (
        <div className="ceeEditer">
          <p style={{ margin: ' 0 0 5px 0 ', fontSize: '14px' }}>Content</p>
          <MarkdownEditor
            value={data.props?.text ?? ''}
            height="200px"
            enablePreview={false}
            data-color-mode="light"
            toolbars={[
              'undo',
              'redo',
              'header',
              'italic',
              'bold',
              'strike',
              'underline',
              'quote',
              'olist',
              'ulist',
              'todo',
              // 'image',
              macro,
            ]}
            onChange={(value, viewUpdate) => {
              const text = value;
              updateData({ ...data, props: { ...data.props, text } });
            }}
          />
        </div>
      )}
      <div
        style={{ color: '#1F1F21', marginTop: '10px', marginBottom: '-26px' }}
        title="GitHub Flavored Markdown and Liquid templating supported"
      >
        GitHub Flavored Markdown and Liquid templating supported.
      </div>
      <BooleanInput
        label="Markdown"
        defaultValue={data.props?.markdown}
        onChange={(markdown) => updateData({ ...data, props: { ...data.props, markdown } })}
      />

      <MultiStylePropertyPanel
        names={['color', 'backgroundColor', 'fontFamily', 'fontSize', 'lineHeight', 'fontWeight', 'textAlign', 'padding']}
        value={data.style}
        onChange={(style) => updateData({ ...data, style })}
      />
    </BaseSidebarPanel>
  );
}
